"""fix letter field names

Revision ID: 0932f0b2cf09
Revises: 1249087053db
Create Date: 2026-08-10 23:50:41.031136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0932f0b2cf09'
down_revision: Union[str, Sequence[str], None] = '1249087053db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('recipient', sa.String(length=100), nullable=False))
    op.add_column('letters', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('letters', 'key_points')
    op.drop_column('letters', 'recipient_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('recipient_type', sa.VARCHAR(length=100), nullable=False))
    op.add_column('letters', sa.Column('key_points', sa.TEXT(), nullable=False))
    op.drop_column('letters', 'content')
    op.drop_column('letters', 'recipient')
    # ### end Alembic commands ###
