"""create letters table

Revision ID: 1249087053db
Revises: ce0fb20b392d
Create Date: 2026-08-10 23:27:17.433931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1249087053db'
down_revision: Union[str, Sequence[str], None] = 'ce0fb20b392d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_type', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('key_points', sa.Text(), nullable=False),
    sa.Column('generated_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_letters_id'), 'letters', ['id'], unique=False)
    op.create_index(op.f('ix_letters_user_id'), 'letters', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_letters_user_id'), table_name='letters')
    op.drop_index(op.f('ix_letters_id'), table_name='letters')
    op.drop_table('letters')
    # ### end Alembic commands ###
