from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.auth.dependencies import get_current_user
from app.core.logging import get_logger
from app.db.database import get_db
from app.models.letter import Letter
from app.models.user import User
from app.repositories.letter_repository import LetterRepository
from app.schemas.letter import (
    LetterRequest,
    LetterResponse,
    LetterHistoryItem,
)
from app.services.ai_service import AIService


router = APIRouter(
    prefix="/letters",
    tags=["Letters"],
)

logger = get_logger(__name__)

service = AIService()
repository = LetterRepository()


@router.post(
    "/generate",
    response_model=LetterResponse,
    summary="Generate a professional letter",
    description="Generate a professional letter using Gemini AI.",
)
def generate_letter(
    request: LetterRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Generate a letter using AI and save it
    for the authenticated user.
    """

    logger.info(
        "Letter generation request received for user=%s",
        current_user.email,
    )

    if request.tone.lower() == "angry":
        logger.warning(
            "Unsupported tone requested: %s",
            request.tone,
        )

        raise HTTPException(
            status_code=400,
            detail="Angry tone is not supported.",
        )

    try:
        generated_letter = service.generate_letter(request)

        logger.info(
            "Letter generated successfully for user=%s",
            current_user.email,
        )

        letter = Letter(
            user_id=current_user.id,
            recipient=request.recipient,
            purpose=request.purpose,
            tone=request.tone,
            content=request.content,
            generated_content=generated_letter,
        )

        saved_letter = repository.create(
            db=db,
            letter=letter,
        )

        logger.info(
            "Letter saved successfully with id=%s",
            saved_letter.id,
        )

        return LetterResponse(
            message="Letter generated successfully.",
            letter=generated_letter,
        )

    except HTTPException:
        raise

    except Exception as e:
        logger.exception(
            "AI letter generation failed."
        )

        raise HTTPException(
            status_code=500,
            detail=f"AI generation failed: {str(e)}",
        )


@router.get(
    "",
    response_model=list[LetterHistoryItem],
    summary="Get letter history",
)
def get_letter_history(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get all letters generated by the authenticated user.
    """

    logger.info(
        "Fetching letter history for user=%s",
        current_user.email,
    )

    letters = repository.get_by_user(
        db=db,
        user_id=current_user.id,
    )

    return letters

@router.get(
    "/{letter_id}",
    response_model=LetterHistoryItem,
    summary="Get a single letter",
)
def get_letter(
    letter_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get a specific letter belonging to the authenticated user.
    """

    logger.info(
        "Fetching letter id=%s for user=%s",
        letter_id,
        current_user.email,
    )

    letter = repository.get_by_id_and_user(
        db=db,
        letter_id=letter_id,
        user_id=current_user.id,
    )

    if letter is None:
        raise HTTPException(
            status_code=404,
            detail="Letter not found",
        )

    return letter

@router.delete(
    "/{letter_id}",
    summary="Delete a letter",
)
def delete_letter(
    letter_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Delete a letter belonging to the authenticated user.
    """

    logger.info(
        "Deleting letter id=%s for user=%s",
        letter_id,
        current_user.email,
    )

    letter = repository.get_by_id_and_user(
        db=db,
        letter_id=letter_id,
        user_id=current_user.id,
    )

    if letter is None:
        raise HTTPException(
            status_code=404,
            detail="Letter not found",
        )

    repository.delete(
        db=db,
        letter=letter,
    )

    logger.info(
        "Letter id=%s deleted successfully",
        letter_id,
    )

    return {
        "message": "Letter deleted successfully.",
        "letter_id": letter_id,
    }